name: Cypress Tests

on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress.io
        uses: cypress-io/github-action@v2.9.7
        with:
          # build: npm run build
          start: npm start
          record: true
          working-directory: KeyCtrl
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 300
          parallel: true
        env:
          CI: ""
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: '468652da-3f69-48de-8c12-35df129e5f47'
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # pass the project ID from the secrets through environment variable
          CYPRESS_PROJECT_ID: '99y4cm'
  